services:

    db:
        image: postgres
        restart: always
        networks:
            - transcendence
        expose:
            - "${DATABASE_PORT}"
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_PASSWORD=${DATABASE_PASS}
            - POSTGRES_USER=${DATABASE_USER}
        volumes:
            - postgres_data:/var/lib/postgresql/data

    redis:
        image: redis
        restart: always
        networks:
            - transcendence
        expose:
            - "${REDIS_PORT}"
        volumes:
            - redis_data:/data

    api:
        build:
            context: .
            dockerfile: ./.docker/api/Dockerfile
        expose:
            - "${API_PORT}"
        volumes:
            - ./application/frontend/static/:/var/www/static
            - ./application/media/:/var/www/media
            - .:/usr/src/app
            - ./application/certs:/usr/src/app/application/certs
        networks:
            - transcendence
        stdin_open: true
        tty: true
        depends_on:
            - db
            - redis

    nginx:
        container_name: nginx
        image: nginx:alpine
        networks:
            - transcendence
        ports:
            - "443:443"
        volumes:
            - ./application/frontend/static/:/var/www/static
            - ./application/media/:/var/www/media
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./application/certs:/etc/nginx/certs
        restart: on-failure:5
        depends_on:
            - api

networks:
  transcendence:
    name: transcendence
    driver: bridge

volumes:
    postgres_data:
    redis_data:
